/*
-- Query: SELECT * FROM sibley_rbac.sub_page
LIMIT 0, 1000

-- Date: 2019-02-11 18:08
*/
INSERT INTO `sub_page` (`id`,`page_id`,`title`,`body`,`type`,`path`,`sort_order`,`last_edit`,`created_by`) VALUES (1,9,'Expectations','<p><strong>Coaches</strong>: Be punctual for all practices &amp; games. Uphold the rules &amp; regulations set forth by the Sibley Recreation Department. Exercise fairness by ensuring playing time for all players. Teach good sportsmanship through both winning &amp; losing. Everyone must shake hands at the end of any scrimmage or game. Remember your player&rsquo;s safety takes precedent over winning a game. Be supportive of all players regardless of skill &amp; provide constructive feedback. Profanity, tobacco, drug or alcohol use will not be tolerated.</p>\n\n<p><strong>Players</strong>: Be on time to ALL practices &amp; games. Play by the rules. Respect the decision of all the coaches &amp; understand that they are acting in the best interests of the team. Promote well-being of teammates through positive encouragement regardless of skill level. Learn and exhibit the values of sportsmanship, honesty, integrity, fairness &amp; safety. Disrespectful conduct of any sort, including profanity, offensive remarks, trash-talking, bullying and taunting will not be tolerated. Put forth your best behavior, represent your team &amp; town and most of all have fun!</p>\n\n<p><strong>Parents</strong>: Attend and enjoy the games, while showing support for ALL of its participants. Allow the coaches to make decisions and run the team. Wait 24 hours after a game before discussing any problems you may have with a coach&rsquo;s strategies or leadership, and do so in a respectful, quiet and individual manner. Act as a role model for good sportsmanship and remain positive whether the team wins or loses. Encourage your child to do the same. Assist in providing your child with a drug free environment &amp; refrain from using tobacco, alcohol or drugs at all youth sporting events. Disrespectful conduct of any sort, including using profanity, obscene gestures, offensive remarks, trash talking, bullying, taunting, boastful celebrations, or other actions that demean individuals or teams will not be tolerated. Altercations (physical or verbal) with players, coaches or officials will not be tolerated &amp; you will be removed from the premises. Do not criticize a player regardless of skill level. Be a role model for your child &amp; encourage the best in them!</p>','section','#expectations',1,'2019-01-27 11:59:23',1);
INSERT INTO `sub_page` (`id`,`page_id`,`title`,`body`,`type`,`path`,`sort_order`,`last_edit`,`created_by`) VALUES (2,9,'I am a test section2','<p>test2</p>\r\n','section','#i_am_a_test_section2',4,'2019-01-31 21:54:29',1);
INSERT INTO `sub_page` (`id`,`page_id`,`title`,`body`,`type`,`path`,`sort_order`,`last_edit`,`created_by`) VALUES (5,9,'I am a test section5','<p>anothe rtest</p>\r\n','section','#i_am_a_test_section5',3,'2019-02-02 11:05:03',1);
INSERT INTO `sub_page` (`id`,`page_id`,`title`,`body`,`type`,`path`,`sort_order`,`last_edit`,`created_by`) VALUES (6,9,'I am a test section6','hows it going number siz?','xlink','http://rec.sibleyiowa.net/',2,'2019-02-02 11:11:32',1);
